### ISSUE TITLE
Use of Trigonometric spline

### ISSUE THREAD

**Issue by supersai007** [mikeroberts3000/flashlight#4]
@mikeroberts3000 : Pondering about the use case of trigonometric spline and its coefficients. Since I could not find documentation, I am asking here. Can you provide an an insight or at the least any reference.

**Comment by mikeroberts3000** [comment]
Hello there. I apologize for the delayed reply. For some reason, I did not get a notification that you had submitted this issue.

When developing our drone shot planning app, I experimented briefly with trigonometric splines. I found that the usual splines used in computer graphics (e.g., Catmull-Rom splines) produced quite unpleasant control trajectories for drone cameras. I was hoping that trigonometric splines would produce better-behaved control trajectories, while still providing the benefits of typical computer graphics splines (e.g., local support).

The control trajectories produced by trigonometric splines were different, but didn't seem to be much better than Catmull-Rom splines. At least in my experience. From here, I decided to give up on local support, and instead try to globally optimize some notion of smoothness. This global approach ended up producing much better-behaved control trajectories than local approaches. For more details, see the supplementary material for our paper, "An Interactive Tool for Designing Quadrotor Camera Shots".

I think my main reference for trigonometric splines was the paper, "Optimal Trigonometric Robot Joint Trajectories" by Simon and Isik.
