### ISSUE TITLE
scipy interp1d usage out of date?

### ISSUE THREAD

**Issue by mmaz** [mikeroberts3000/flashlight#6]
I was getting the following error from `scipy.interpolate.interp1d()` in `interpolate_utils.resample_scalar_wrt_scalar()`:

```python
 in reparameterize_curve
    t_user_progress_cubic = interpolate_utils.resample_scalar_wrt_scalar(l_cum_norm,t_p_linspace_norm,user_progress,kind="cubic")
  File "code/lib/flashlight/interpolate_utils.py", line 27, in resample_scalar_wrt_scalar
    x_new         = x_interp_func(t_new)
  File "scipy/interpolate/polyint.py", line 79, in __call__
    y = self._evaluate(x)
  File "scipy/interpolate/interpolate.py", line 664, in _evaluate
    below_bounds, above_bounds = self._check_bounds(x_new)
  File "site-packages/scipy/interpolate/interpolate.py", line 696, in _check_bounds
    raise ValueError("A value in x_new is above the interpolation "

ValueError: A value in x_new is above the interpolation range.
```

From this [StackOverflow post](https://stackoverflow.com/a/45446546) I'm guessing this is from an update to scipy, so I have added in `fill_value='extrapolate'` in [`interpolate_utils.py`](https://github.com/mikeroberts3000/flashlight/blob/0f549f03a908b6642337b2d9c77bb624de98be0d/code/lib/flashlight/interpolate_utils.py#L26):

```diff
-    x_interp_func = scipy.interpolate.interp1d(t,x,kind=kind)
+    x_interp_func = scipy.interpolate.interp1d(t,x,kind=kind, fill_value='extrapolate')
```

I am guessing this was the default behavior of the version of scipy that flashlight was written with, (but I haven't looked in scipy changelogs to check). The generated trajectory in the [notebook example](http://nbviewer.jupyter.org/github/mikeroberts3000/flashlight/blob/master/code/examples/jupyter/08%20-%20Computing%20the%20control%20forces%20required%20for%20a%203D%20quadrotor%20to%20follow%20a%20trajectory.ipynb) looks good though.

Thanks again for this great library! Excited to start using it more!

**Platform info**

I'm using `scipy 1.1.0`: on OSX:

```bash
$ conda list | grep scipy
scipy                     1.1.0           py27_blas_openblash7943236_201  [blas_openblas]  conda-forge
```

**Comment by mikeroberts3000** [comment]
Hello there. I apologize for the delayed reply. For some reason, I did not get a notification that you had submitted this issue.

I don't think the behavior of scipy.interpolate.interp1d has changed recently. I don't think scipy.interpolate.interp1d supports extrapolation by default (in current or previous versions), and neither does my interpolate_utils.py wrapper. For my use cases, it is a user error if I am accidentally trying to extrapolate. If you want interpolate_utils.py to support extrapolation, then your local modification appears to be correct.
